name: foss_ui
description: >-
  An open-source Flutter UI library. Unofficial port inspired by coss.com/ui,
  built on Flutter-native theming and golden-tested widgets.
version: 0.0.1
homepage: https://narayann.dev
repository: https://github.com/narayann7/foss_ui
issue_tracker: https://github.com/narayann7/foss_ui/issues

environment:
  sdk: ^3.11.5
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
